#pragma once
#include <Arduino.h>

#define MCP23017_DEFAULT_ADDR 0x20
#define MTS_STEPPER_TYPE_16_REV 513
#define MTS_STEPPER_TYPE_64_REV 2038

enum MTS_STEPPER_TYPE {
	MTS_STEPPER_TYPE_16 = 0,
	MTS_STEPPER_TYPE_64
};

enum MTS_STEPPER_STEP_SIZE {
	MTS_STEPPER_FULL_STEP = 0,
	MTS_STEPPER_HALF_STEP
};

enum MTS_STEPPER_ID {
	MTS_STEPPER_1 = 0,
	MTS_STEPPER_2,
	MTS_STEPPER_3,
	MTS_STEPPER_4
};


#define MTS_STEPPER_COUNT 4
enum MTS_STEPPER_PHASE {
	MTS_STEPPER_PHASE_1 = 0,
	MTS_STEPPER_PHASE_2,
	MTS_STEPPER_PHASE_3,
	MTS_STEPPER_PHASE_4,
	MTS_STEPPER_PHASE_5,
	MTS_STEPPER_PHASE_6,
	MTS_STEPPER_PHASE_7,
	MTS_STEPPER_PHASE_8,

	MTS_STEPPER_PHASE_DISABLE = -1
};